### ISSUE TITLE
__slots__ fail in python 3.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niltonvolpato/python-progressbar#23]
```
What steps will reproduce the problem?
1. Install python 3.3
2. python setup.py build

What is the expected output? What do you see instead?

[root@archbuild progressbar-2.3]# python setup.py  build
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import progressbar
  File "/build/src/progressbar-2.3/progressbar/__init__.py", line 59, in <module>
    from progressbar.widgets import *
  File "/build/src/progressbar-2.3/progressbar/widgets.py", line 121, in <module>
    class FileTransferSpeed(Widget):
  File "/usr/lib/python3.3/abc.py", line 130, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
ValueError: 'format' in __slots__ conflicts with class variable


What version of the product are you using? On what operating system?
Archlinux with python 3.3

```

Original issue reported on code.google.com by `sebastien.luttringer` on 29 Sep 2012 at 8:05
- Merged into: #21

**Comment by DSLituiev** [comment]
The version on https://pypi.python.org/pypi/progressbar is still outdated and has this bug
