### ISSUE TITLE
Your own examples don't run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niltonvolpato/python-progressbar#35]
```
What steps will reproduce the problem?
1. virtualenv .
2. source bin/activate
3. pip install progressbar
4. wget http://python-progressbar.googlecode.com/hg/examples.py
5. python examples.py

What is the expected output? What do you see instead?

The expected output is 19 different examples of progress bars.

The actual output is:

    Traceback (most recent call last):
    File "examples.py", line 7, in <module>
        from progressbar import AnimatedMarker, Bar, BouncingBar, Counter, ETA, \
    ImportError: cannot import name AnimatedMarker

What version of the product are you using? On what operating system?

pip installs version 2.2. The operating system is linux mint (an ubuntu 
derivative).

Please provide any additional information below.

My initial attempts to use this library were as simple as:

    python -c 'import time
    from progressbar import ProgressBar          
    progress = ProgressBar()
    for i in progress(range(80)):
      time.sleep(0.01)'

(based on example 19). This does not work:

    Traceback (most recent call last):
      File "<string>", line 5, in <module>
    TypeError: 'ProgressBar' object is not callable
```

Original issue reported on code.google.com by `ma...@gapps.semantico.com` on 25 Feb 2014 at 10:48

**Comment by niltonvolpato** [comment]
The version in pypi was older than the version in the repository. But it has just been updated. This should work now.

https://pypi.org/manage/project/progressbar/release/2.5/
