### ISSUE TITLE
Import error in examples.py

### ISSUE THREAD

**Issue by thekswenson** [niltonvolpato/python-progressbar#59]
I try to run examples.py and get:

> => python examples.py 
> Traceback (most recent call last):
>   File "examples.py", line 7, in <module>
>     from progressbar import AnimatedMarker, Bar, BouncingBar, Counter, ETA, \
> ImportError: cannot import name AdaptiveETA

**Comment by thekswenson** [comment]
All good.

**Comment by RuiApostolo** [comment]
I'm still having this issue, on version 2.5 (python2.7):

```
$ sudo -H pip install progressbar
$ wget https://raw.githubusercontent.com/niltonvolpato/python-progressbar/master/examples.py
$ python2.7 examples.py
Traceback (most recent call last):
  File "examples.py", line 7, in <module>
    from progressbar import AnimatedMarker, Bar, BouncingBar, Counter, ETA, \
  File "/home/rfapostolo/data/test/progressbar.py", line 7, in <module>
    from progressbar import AnimatedMarker, Bar, BouncingBar, Counter, ETA, \
ImportError: cannot import name AnimatedMarker
```
