### ISSUE TITLE
Example 19 from examples.py ends with "AttributeError: next_update"

### ISSUE THREAD

**Issue by thekswenson** [niltonvolpato/python-progressbar#60]
> Running: Example 19
> Traceback (most recent call last):
>   File "examples.py", line 210, in <module>
>     for example in examples: example()
>   File "examples.py", line 20, in wrapped
>     fn()
>   File "examples.py", line 204, in example19
>     for i in pbar([]):
>   File "/usr/lib/python2.7/dist-packages/progressbar/__init__.py", line 184, in __next__
>     self.finish()
>   File "/usr/lib/python2.7/dist-packages/progressbar/__init__.py", line 321, in finish
>     self.update(self.maxval)
>   File "/usr/lib/python2.7/dist-packages/progressbar/__init__.py", line 276, in update
>     if not self._need_update(): return
>   File "/usr/lib/python2.7/dist-packages/progressbar/__init__.py", line 251, in _need_update
>     if self.currval >= self.next_update or self.finished: return True
> AttributeError: next_update

**Comment by niltonvolpato** [comment]
That seems to be working for me. Can you try on a clean repository synced to head and see if it still happens?

**Comment by thekswenson** [comment]
It's OK now.
