### ISSUE TITLE
Names with % break it

### ISSUE THREAD

**Issue by kittenswolf** [niltonvolpato/python-progressbar#68]
```
>>> x = Bar("%", max=100)
>>> x.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kittenswolf/.local/lib/python3.6/site-packages/progress/__init__.py", line 120, in next
    self.update()
  File "/home/kittenswolf/.local/lib/python3.6/site-packages/progress/bar.py", line 36, in update
    message = self.message % self
ValueError: incomplete format```

**Comment by NiltonVolpato** [comment]
Yeah, maybe we should escape the input. A workaround is using "%%" for now
